spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/wallet
spring.datasource.username=wallet
spring.datasource.password=wallet
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

